config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :teams
  resources :tournaments do
    member do
      get :play_index
      post :play_start
      get :results
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "tournaments#index"

  get "/tournaments/:tournament_id/teams", \
    to: "teams#by_tournament", as: "tournament_teams"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  include AASM

  aasm do
    state :init, initial: true
    state :groups
    state :playoff
    state :finished
  end
  alias_attribute :stage, :aasm_state
  enum aasm_state: {
    init: 0,
    groups: 1,
    playoff: 2,
    finished: 3
  }

  belongs_to :tournament

  # rubocop:disable Rails/InverseOf
  has_one :team1,
    dependent: :nullify,
    class_name: "Team",
    primary_key: :team1_id,
    foreign_key: :id

  has_one :team2,
    dependent: :nullify,
    class_name: "Team",
    primary_key: :team2_id,
    foreign_key: :id

  has_one :winner,
    dependent: :nullify,
    class_name: "Team",
    primary_key: :winner_id,
    foreign_key: :id
  # rubocop:enable Rails/InverseOf

  def self.best_in_group(ids, order=:desc)
    where(winner_id: ids).
      group(:winner_id).
      order(count_all: order).
      count.
      map { |id, _| id }
  end

  # rubocop:disable Rails/SkipsModelValidations
  def team1=(team)
    return unless team

    update_column(:team1_id, team.id)
  end

  def team2=(team)
    return unless team

    update_column(:team2_id, team.id)
  end

  def winner=(team)
    return unless team

    update_column(:winner_id, team.id)
  end
  # rubocop:enable Rails/SkipsModelValidations
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  attr_accessor :current_tournament

  # rubocop:disable Rails/HasAndBelongsToMany
  has_and_belongs_to_many :tournaments
  # rubocop:enable Rails/HasAndBelongsToMany

  belongs_to :winner_tournament,
    class_name: "Tournament",
    inverse_of: :winner,
    primary_key: :winner_id,
    foreign_key: :id,
    dependent: nil,
    required: false

  belongs_to :finalist_tournament,
    class_name: "Tournament",
    inverse_of: :finalist,
    primary_key: :finalist_id,
    foreign_key: :id,
    dependent: nil,
    required: false

  accepts_nested_attributes_for :tournaments

  validates :name, presence: true

  class GroupSizeValidator < ActiveModel::Validator
    def validate(record)
      tournament = record.current_tournament
      return false unless tournament

      if tournament.teams.count >= PlayService::GROUP_SIZE
        record.errors.add(:name, "Teams count (#{ PlayService::GROUP_SIZE }) exceeded")
        raise ::ActiveModel::ValidationError.new(record)
      else
        true
      end
    end
  end
  validates_with GroupSizeValidator
end

app/models/tournament.rb
# frozen_string_literal: true

class Tournament < ApplicationRecord
  include AASM

  aasm do
    state :draft, initial: true
    state :in_progress
    state :done
  end

  # rubocop:disable Rails/UniqueValidationWithoutIndex
  validates :name, presence: true, uniqueness: true
  # rubocop:enable Rails/UniqueValidationWithoutIndex

  alias_attribute :status, :aasm_state
  enum aasm_state: {draft: 0, in_progress: 1, done: 2}

  validates :aasm_state, presence: true

  has_many :games, dependent: :destroy

  # rubocop:disable Rails/HasAndBelongsToMany
  has_and_belongs_to_many :teams
  # rubocop:enable Rails/HasAndBelongsToMany

  has_one :winner,
    dependent: :nullify,
    class_name: "Team",
    primary_key: :winner_id,
    foreign_key: :id,
    inverse_of: :winner_tournament

  has_one :finalist,
    dependent: :nullify,
    class_name: "Team",
    primary_key: :finalist_id,
    foreign_key: :id,
    inverse_of: :finalist_tournament

  delegate :count, to: :teams, prefix: true

  def full_group?
    PlayService::GROUP_SIZE == teams_count
  end

  def playable?
    full_group? && !done?
  end

  # rubocop:disable Rails/SkipsModelValidations
  def winner=(team)
    return unless team

    update_column(:winner_id, team.id)
  end

  def finalist=(team)
    return unless team

    update_column(:finalist_id, team.id)
  end
  # rubocop:enable Rails/SkipsModelValidations

  def self.to_a
    all.each_with_object([]) do |t, memo|
      memo << [t.name, t.id]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  expose :tournaments_array, -> { Tournament.to_a }
  expose :tournament, -> { Tournament.find(tournament_id) }
  expose :teams, -> do
    if params[:tournament_id]
      tournament.teams
    else
      Team.all
    end
  end

  expose :team

  def index; end

  def by_tournament
    render :index
  end

  def show; end

  def new; end

  def edit; end

  def create
    team.current_tournament = tournament
    if team.save
      team.tournaments << tournament
      redirect_to team, notice: "Team was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  rescue ActiveModel::ValidationError => e
    render :new, status: :unprocessable_entity, message: e
  rescue ActiveRecord::RecordNotUnique => e
    team.errors.add(:name, "is already exists")
    render :new, status: :unprocessable_entity, message: e
  end

  def update
    team.current_tournament = tournament
    if team.update(team_params)
      team.tournaments << tournament
      redirect_to team, notice: "Team was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  rescue ActiveModel::ValidationError => e
    render :new, status: :unprocessable_entity, message: e
  rescue ActiveRecord::RecordNotUnique => e
    team.errors.add(:name, "is already exists in this tournament")
    render :new, status: :unprocessable_entity, message: e
  end

  def destroy
    team.destroy!
    redirect_to teams_url, notice: "Team was successfully destroyed."
  end

  private

    def tournament_id
      params[:tournament_id] || params[:team][:tournament_id]
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).
        permit(:name, tournaments_attributes: [:id, :tournament_id])
    end
end

app/controllers/tournaments_controller.rb
# frozen_string_literal: true

class TournamentsController < ApplicationController
  expose :tournaments, -> { Tournament.all }
  expose :tournament
  expose :teams_array, -> { tournament.teams }

  def index; end

  def show; end

  def new; end

  def edit; end

  # GET
  def play_index
    render :play_index
  end

  # POST
  def play_start
    service = PlayService.new(tournament)
    service.play!

    redirect_to results_tournament_path(tournament), \
      notice: "Tournament was successfully finished."
  rescue StandardError => e
    tournament.errors.add(:base, e.message)
    tournament.errors.add(:base, e.backtrace.first)

    render :play_index
  end

  def results; end

  def create
    if tournament.save
      redirect_to tournament_path(tournament), \
        notice: "Tournament was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if tournament.update(tournament_params)
      redirect_to tournament, notice: \
        "Tournament was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    tournament.destroy!
    redirect_to tournaments_url, notice: \
      "Tournament was successfully destroyed."
  end

  private

    # Only allow a list of trusted parameters through.
    def tournament_params
      params.require(:tournament).permit(:name, :status, :winner, :finalist)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/helpers/tournaments_helper.rb
# frozen_string_literal: true

module TournamentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="bg-light md">
    <div class="d-flex justify-content-center p-3 mb-2 bg-light bd-example">
      <a class="btn btn-primary" role="button" href="/">Home</a> &nbsp;
      <a class="btn btn-primary" role="button" href="<%= tournaments_path %>">Tournaments</a> &nbsp;
      <a class="btn btn-primary" role="button" href="<%= teams_path %>">Teams</a> &nbsp;
    </div>

    <% if notice.present? %>
      <div id="notice" class="alert alert-success alert-dismissible fade show"><%= notice %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tournaments/_form.html.erb
<%= form_with(model: tournament, local: true) do |form| %>
  <% if tournament&.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3 alert alert-success" role="alert">
    <b><%= form.label :status, class: "form-label" %>:</b>
    <%= tournament.aasm_state&.humanize %>
  </div>

  <div class="mb-3 actions">
    <%= form.button 'Save', :class => 'btn btn-primary' %>
  </div>

<% end %>

app/views/tournaments/edit.html.erb
<h1 class="d-flex justify-content-center p-3 mb-2 bg-light">Editing Tournament</h1>

<div class="bd-layout container-xxl">
<%= render 'form', tournament: tournament %>

<%= link_to 'Show', tournament %> |
<%= link_to 'Back', tournaments_path %>
</div>

app/views/tournaments/index.html.erb
<h1 class="d-flex justify-content-center p-3 mb-2 bg-light">Tournaments</h1>

<div class="bd-layout container-xxl">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Status</th>
      <th scope="col">Winner</th>
      <th scope="col">Finalist</th>
      <th scope="col">Play</th>
      <th scope="col">Results</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% tournaments.each do |tournament| %>
      <tr>
        <td><%= link_to tournament.name, tournament, class: "btn btn-secondary", role: "button" %></td>
        <td><%= tournament.status.humanize %></td>
        <td>
          <% if tournament.winner %>
            <%= link_to tournament.winner.name, tournament.winner, class: "btn btn-success", role: "button"%>
          <% end %>
        </td>
        <td>
          <% if tournament.finalist %>
            <%= link_to tournament.finalist.name, tournament.finalist, class: "btn btn-success", role: "button" %>
          <% end %>
        </td>
        <td>
          <% unless tournament.done? %>
            <%= link_to 'Play Tournament', play_index_tournament_path(tournament), class: "btn btn-danger", role: "button" %>
          <% end %>
        </td>
        <td>
          <% if tournament.done? %>
            <%= link_to 'Display Resluts', results_tournament_path(tournament), class: "btn btn-success", role: "button" %>
          <% end %>
        </td>
        <td><%= link_to 'Teams', tournament_teams_url(tournament) %></td>
        <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
        <td><%= link_to 'Destroy', tournament, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create Tournament', new_tournament_path, class: "btn btn-danger d-flex justify-content-center", role: "button" %>
<br/><br/>
</div>

app/views/tournaments/new.html.erb
<h1 class="d-flex justify-content-center p-3 mb-2 bg-light">New Tournament</h1>

<div class="bd-layout container-xxl">
<%= render 'form', tournament: tournament %>

<%= link_to 'Back', tournaments_path %>
</div>

app/views/tournaments/play_index.html.erb
<h1 class="d-flex justify-content-center p-3 mb-2 bg-light">Play Tournament: <%= tournament.name %></h1>

<div class="bd-layout container-xxl">
  <%= form_with url: play_start_tournament_path, local: true do |form| %>

    <% if tournament.errors.any? %>
      <div class="alert alert-danger">
        <h3><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being played:</h3>

        <ul>
          <% tournament.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% unless tournament.full_group?  %>
      <div id="notice" class="alert alert-warning alert-dismissible fade show">
        To start game teams count in the tournir should be
        <b><%= ::PlayService::GROUP_SIZE %></b>.
        Please,
        <%= link_to "add more teams", new_team_path %>.
      </div>
    <% end %>

    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Teams:</h5>
        <ol class="list-group list-group-flush">
          <% teams_array.each do |t| -%>
            <li class="list-group-item">
              <%= link_to(t.name, t) %>
            </li>
          <% end %>
        </ol>
      </div>
      <div class="actions card-body">
        <% if tournament.playable? %>
          <%= form.button 'Play Tournament', :class => 'btn btn-danger' %>
        <% end %>

        <% unless tournament.full_group? %>
          <%= link_to 'Add Team', new_team_path, class: "btn btn-danger d-flex justify-content-center", role: "button"  %>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

app/views/tournaments/results.html.erb
<h1 class="d-flex justify-content-center p-3 mb-2 bg-light">Results for tournament: <%= tournament.name %></h1>

app/views/tournaments/show.html.erb
<h1 class="d-flex justify-content-center p-3 mb-2 bg-light">
  Tournament: <%= tournament.name %>
</h1>

<div class="bd-layout container">
<div class="row">
  <div class="col-1">
    <strong>Name:</strong>
  </div>
  <div class="col-3">
    <%= tournament.name %>
  </div>
</div>

<div class="row">
  <div class="col-1">
    <strong>Status:</strong>
  </div>
  <div class="col-3">
    <%= tournament.status&.humanize %>
  </div>
</div>

<div class="row">
  <div class="col-1">
    <strong>Winner:</strong>
  </div>
  <div class="col-3">
    <% if tournament.winner %>
      <%= link_to tournament.winner.name, tournament.winner %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-1">
    <strong>Finalist:</strong>
  </div>
  <div class="col-3">
    <%= tournament.finalist %>
  </div>
</div>

<%= link_to 'Edit', edit_tournament_path(tournament) %> |
<%= link_to 'Back', tournaments_path %>
</div>